{
 "title": "System Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Startup Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application_started_time_seconds",
     "legendFormat": "Started Time"
    },
    { "expr": "application_ready_time_seconds", "legendFormat": "Ready Time" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} used" },
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} committed" }
   ]
  },
  {
   "title": "Active Kafka Listeners",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count",
     "legendFormat": "KafkaListener count"
    }
   ]
  },
  {
   "title": "Database Connection Pool (HikariCP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "Active Connections" },
    { "expr": "hikaricp_connections_idle", "legendFormat": "Idle Connections" },
    { "expr": "hikaricp_connections_max", "legendFormat": "Max Connections" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "HTTP /actuator/prometheus"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Process CPU" },
    { "expr": "system_cpu_usage", "legendFormat": "System CPU" }
   ]
  }
 ]
}